### ISSUE TITLE
Partial not added when inline_errors == 'display'

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#102]
Hello,

I noticed a strange behavior that looks like more than a bug than a by design choice.

When you enable inline errors on fields, the flash.htm partial is no longer added to the form.

To me, it's a problem for 2 reasons : 
- The flash partial handle extra javascript you put in "JS on error" and you probably want to see this code executed when you submit the form and it return errors (even if it's inline errors)
- You should be able to display both alert message and inline error on fields if you want to.

That's why I think that flash.htm should always be inserted to the form, inline errors or not.

**Comment by LordBuzzard** [comment]
@Alex360hd Hi Alex,

Hi recently had to face this issue and the following is what I have done to unable inline errors.

Very often you will have to look at the code to get the full capabilities and internal logic behind October CMS as it's documentation isn't complete (even if they have documented a lot)
By digging into the exception handling when using AjaxHandlers you will realise that VaidationExceptions (when combined with a Validator instance) will instanciate fields and messages for these fields : 
```
    /**
     * Evaluate errors.
     */
    protected function evalErrors()
    {
        foreach ($this->errors->getMessages() as $field => $messages) {
            $this->fields[$field] = $messages;
        }

        $this->message = $this->errors->first();
    }
```

Then when you throw your ValidationException to the AjaxHandler controller ( `execAjaxHandlers()` ) it uses the fields and messages from the ValidationException to create and thow an AjaxException (which is the correct thing to do because we are executing Ajax calls) : 

```
                /*
                 * Handle validation errors
                 */
                $responseContents['X_OCTOBER_ERROR_FIELDS'] = $ex->getFields();
                $responseContents['X_OCTOBER_ERROR_MESSAGE'] = $ex->getMessage();
                throw new AjaxException($responseContents);
```

Now, you have reproduce this behaviour when using the plugin MagicForm at the appropriate time.
For me it was while building the exception response : 

```
    private function exceptionResponse($validator, $params)
    {

        // FLASH PARTIAL
        $flash_partial = $this->property('messages_partial', '@flash.htm');

        // EXCEPTION RESPONSE
        $response = ['#' . $this->alias . '_forms_flash' => $this->renderPartial($flash_partial, $params)];

        // INCLUDE ERROR FIELDS IF REQUIRED
        if ($this->property('inline_errors') != 'disabled') {
            $ex = new ValidationException($validator);
            $response['X_OCTOBER_ERROR_FIELDS'] = $ex->getFields();
            $response['X_OCTOBER_ERROR_MESSAGE'] = $ex->getMessage();
        }

        return $response;
    }
```

Hope it can help you & other people with similar issues.

**Comment by skydiver** [comment]
Hello @LordBuzzard 

Do you wanna send a PR?


Thanks.-

**Comment by Alex360hd** [comment]
Wow, thanks for this detaillled message. When I have some time I will test that and create the PR if it works
