### ISSUE TITLE
Uploaded attachment not deleting

### ISSUE THREAD

**Issue by raftelco** [skydiver/october-plugin-forms#114]
Hello. There are several bugs regarding to upload form. 

First case: When I upload file and close the browser file remains.
Second case: When I delete record (soft delete nor permanent delete from db) file remains physically and also in system_files table.

**Comment by skydiver** [comment]
Hello @raftelco 

As you may notice, the upload component has always been a beta feature.

Is based on an already existing AJAX upload plugin for October, but never worked at 100%.

A few time i've looking for an alternative but involves a lot of time re-doing all the upload stuff.

As always, PRs are welcome, if anyone has time to help with this.

**Comment by Alex360hd** [comment]
I already tried to revamp this part and I abandonned cause it add lot of complexity to magicform itself just to handle upload.

My feedback after deeply looking to the code is that the upload feature would need to be rewritten to be simpler to implement/configure/use.

The perfect solution to me would be to keep the magicform phylosophy that works extremly well : you write the HTML of your and magicform handle the rest "magically".

So, if you apply this philosophy to upload, your job as a form builder would be to write your form fields in html, like the others fields : 

For single upload field
    <input type="file" name="myfile" />

For multiple upload fileds
    <input type="files" name="myfiles" multiple />

Then, magicform component would provide a new "Upload" configuration group, where you can define some settings for each fields, for example : "accepted extension type", "max file size", "upload path" etc... (all file upload useful options). I imagine that widget like the one you have to define required fields, a kind of table where you can add several lines (one for each upload field). For example : 

| file  | .png .jpg|1MB|/storage/upload/magicform/image|etc... |
|-------|------------------------------------------------------|
| files | .pdf|5MB|/storage/upload/magicform/documents|etc...  |

That upload fields would also be compatible with the already existing "required" and "allowed_fields" options.

That would be a lot of work to do, that's why I abandonned actually

**Comment by skydiver** [comment]
In my experience, AJAX uploads was always a nightmare.

On this case, there is an extra layer of complexity with OctoberCMS attachment files and uploads before store the form data.


There is an alternative, **a not fancy one**, that involves to create a non AJAX upload form, just submit the form, store the data and upload the files then reload the page.

We can scroll to the form using javascript or redirect to a new page.

PROS: we can give a solution for the users who needs to upload files
CONS: the flow sounds odd and ugly.

**Comment by raftelco** [comment]
Any idea for temporary solution?

**Comment by Alex360hd** [comment]
What about using [jQuery File Upload](http://blueimp.github.io/jQuery-File-Upload/) ? It seems it can handle the file upload to the server.

**Comment by Alex360hd** [comment]
@raftelco : The temporary solution is to use the actual upload feature of magic form, or to work on a PR to improve this part of the plugin

**Comment by skydiver** [comment]
@raftelco you can "cleanup" orphan files, look here: https://octobercms.com/docs/database/relations#cleanup-bindings
