### ISSUE TITLE
Need help to add anti spam feature, such as mewebstudio/captcha

### ISSUE THREAD

**Issue by alanhwi** [skydiver/october-plugin-forms#176]
Hi,

Good job! this is a very useful plugin.

If the plugin adds picture verification function, such as mewebstudio/captcha (Captcha for Laravel), This plugin will be more perfect！

Because Google is not available in some regions around the world(Google reCaptcha is invalid), so if I provide Website message module for these regions, I must use image verification codes to prevent spam mail.

I searched all the Contact form Plugins in Octobercms, But I didn't find any contact form plugin with picture verification code. If the plugin adds picture verification function, This Plugin will benefit more people. I hope to consider adding this function, thank you!

**Comment by damsfx** [comment]
Same as #163

**Comment by wi-wi** [comment]
For you and others with similar problems.

1. add this line on top in the partial **genericForm/default.htm**

<script src='https://www.google.com/recaptcha/api.js' async defer></script>

this calls the google api. no site key needed since the api takes your domain from your url, so knows the key.

2. in the partial **genericForm/default.htm**, replace the line

{% partial '@recaptcha' %} 

with:

    <div id="{{ __SELF__ }}" class="g-recaptcha" data-sitekey="{{ __SELF__.settings.recaptcha_site_key }}" data-theme="{{ __SELF__.property('recaptcha_theme') }}" data-type="{{ __SELF__.property('recaptcha_type') }}" data-size="{{ __SELF__.property('recaptcha_size') }}"></div>



==================

3. so **genericForm/default.htm** looks like this:


<script src='https://www.google.com/recaptcha/api.js' async defer></script>  

<form data-request="{{ __SELF__ }}::onFormSubmit">

    {{ form_token() }}

    <div id="{{ __SELF__ }}_forms_flash"></div>

    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control">
    </div>

    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" class="form-control">
    </div>

    <div class="form-group">
        <label for="subject">Subject:</label>
        <input type="text" id="subject" name="subject" class="form-control">
    </div>

    <div class="form-group">
    <label for="comments">Comments:</label>
        <textarea id="comments" name="comments" rows="8" cols="80"></textarea>
    </div>

    <div class="form-group">
    <div id="{{ __SELF__ }}" class="g-recaptcha" data-sitekey="{{ __SELF__.settings.recaptcha_site_key }}" data-theme="{{ __SELF__.property('recaptcha_theme') }}" data-type="{{ __SELF__.property('recaptcha_type') }}" data-size="{{ __SELF__.property('recaptcha_size') }}"></div>
    </div>
    <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>
</form>
