### ISSUE TITLE
No buttons on component input fields

### ISSUE THREAD

**Issue by zlobec** [skydiver/october-plugin-forms#217]
Hi,

I'm on latest version and don't get any submit button on recepient field. See image attached. Is it just me?

![Screenshot from 2020-09-21 12:59:59](https://user-images.githubusercontent.com/6809572/93759495-8f2a2d80-fc0a-11ea-8d97-a514785b5380.png)

**Comment by bdwilton** [comment]
Yes I have the same issue on the recipient field

**Comment by Nismoteika** [comment]
i have too, i hotfix this by developer tools copy textarea text to div.form-control (html edit)
![Screenshot_10](https://user-images.githubusercontent.com/20801893/93899977-8cf4cb80-fcfd-11ea-8f02-a80a62fe5dd5.png)

**Comment by patrikaagit** [comment]
Hi, it looks like I have found where this problem comes from.

1. Locate file /modules/system/assets/ui/storm-min.js
2. go to line 5808,
3. and change
`<textarea class="form-control size-small field-textarea" name="name" value=""/>`
to
`<textarea class="form-control size-small field-textarea" name="name" value=""></textarea>`.

**Comment by zlobec** [comment]
This seems OK in the source file... See here: https://github.com/octobercms/october/blob/d49266ad90246fcf90565de8ccdcdbad492de0fe/modules/system/assets/ui/js/inspector.editor.text.js#L50

Compile error?

**Comment by weidmaster** [comment]
@zlobec @patrikaagit This works! Now we just need to wait for October to update the version.
