### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by alimbekoff96** [skydiver/october-plugin-forms#223]
Hi, there is a bug here for half a year already, when they fix it. When you enter to indicate recipients and senders 
![2020-11-30](https://user-images.githubusercontent.com/69335697/100570773-baf91c00-32fb-11eb-9c38-0ba58c28876f.png)

**Comment by bmiskoski** [comment]
I had troubles with the bug on my newer projects don't really know why it is there, because on my older project (older version of the plugin) i didn't see this bug.

You can manually add message recipients from your .htm page.

Add this lines of code:

mail_enabled = 1
mail_subject = "Your message subject here**"
mail_recipients[] = "test@test.com"

Afterwards in the CMS the bug will be fixed.

Hope this helps.

**Comment by skydiver** [comment]
Related to https://github.com/skydiver/october-plugin-forms/issues/217
