### ISSUE TITLE
File uploaded on the storage but not displayed in the record and email.

### ISSUE THREAD

**Issue by zunnurs01** [skydiver/october-plugin-forms#247]
Hi, I found that the upload only work on the first upload. Then the upload not working anymore. On the storage, the new files uploaded existed. I check the database and found that there is no relationship between the files and the plugin. Please help.

**Comment by tfprado** [comment]
@zunnurs01 are you overwriting the component markup? I can list out some of the issues I had when using the uploader to see if that helps you!
If you are overwritting component markup make sure to use {{ form_ajax(__SELF__::onFormSubmit) }} instead of a <form data-request="onFormSubmit>, as you wil need the token and session that get added for the uploader plugin to work.
I would also make sure your component has all the correct properties 
<img width="405" alt="Screen Shot 2021-06-10 at 12 33 03 PM" src="https://user-images.githubusercontent.com/3441074/121563062-12352300-c9e8-11eb-9e05-0e56b4d46ffa.png">
