### ISSUE TITLE
Add a small option to choose the partial name you want to use

### ISSUE THREAD

**Issue by Zmove** [skydiver/october-plugin-forms#33]
Hello,

I work on a project with many different forms. I already know the default way of october to override a default partial with your custom one using subdirectory and component alias.

The problem is that you can only have 1 form per subdirectory for example :

>/partials/contact/default.htm
>/partials/quote/default.htm
>/partials/survey1/default.htm
>etc...

I would like to group all my magic form into one subdirectory, which would be far more easy to maintain, for example :

> /partials/forms/contact.htm
> /partials/forms/quote.htm
> /partials/forms/survey1.htm
> etc...

Would it be possible to add a small option when you configure the component "partial to use", to be able to precide the filename of the partial you want to use instead of "default.htm"

Thanks, and continue that great work !

Best regards,

Alex

**Comment by skydiver** [comment]
Hello @Zmove 

After looking on October documentation and investigating the source, i can't find a way to rename default components html.

Do you know any alternative or a plugin doing this?


Thanks.-

**Comment by Alex360hd** [comment]
@skydiver 

I don't know any plugins to do that (maybe it's not possible cause hardcoded in october core) but I made some progress.

I could customize the path and name of partial file for my form by using partials instead of components.

Instead of doing (lets assume my form have the _contact_ alias
    {% component emptyForm %}

I do
    {% partial 'forms/contact.htm' __SELF__ = 'contact' %}

In my form.contact.htm partial, I have the same code than the genericForm/default.htm

I could remove the __SELF__ = 'contact' variable defined in my partial and replace all the {{ __SELF__ }} twig variables in the partial by {{ contact }} but I prefer to keep the default code in the partial (but that's just a personal preference).

I encountered 2 problems :

**The first one** (but can be fixed easily)
About the captcha, calling the partial {{ partial '@recaptcha' }} throw me an error cause october cannot find the partial, not sure what the @ prefix mean, but I replaced that code by {{ partial 'forms/recaptcha' __SELF__ = 'contact' }} and I replaced the default component partial by mine. It works.

**The second one (cannot be fixed actually without plugin update)**
Second problem (more annoying) is about the success message. It's not flexible enought to magically put the result of the partial in a div with specific ID. It would be better to do something like this :

    <div id="{{ forms }}_forms_flash">{% partial '@flash.htm' %}</div>

And, in the partial, to add a condition to output nothing if there is nothing to display. (In fact, even the wrapper div could be inside the flash partial to avoid empty div if there is no messages).

    {% if flash %}
      <div class="alert alert-{{ type }}">..........
    {% endif %}

Like that, I could call my own partial for the flash message using the same way than the captcha, by replacing {% partial '@flash' %} by {% partial 'forms/flash' %}

This is the recommanded way to proceed to move default component markup to custom partial. markup). [See documentation about it](https://octobercms.com/docs/cms/components#moving-default-markup)

**Comment by gwugodevco** [comment]
Another way to do use: overriding component's partial as described [here](https://octobercms.com/docs/cms/components#overriding-partials)

1. Create directory in your theme's partial directory with the name of your form-component (note: if you alias your form, the directory name should be the alias)
2. Create default.htm in that new directory.

That should do.

**Comment by Alex360hd** [comment]
Hello,

Thank you for the reply but it does bring answer to the initial problem.

By doing as you suggest, if you have 20 different form, you end with something like this :

> form1/default.htm
> form2/default.htm
> form3/default.htm
> form4/default.htm

It's a lot of different folder for the same feature provided by the same plugin ! When you have lots of form, it would be better to have something like this

> forms/form1.htm
> forms/form2.htm
> forms/form3.htm
> etc....

There is a solution to group all forms inside one folder as described in my previous post. It's not ideal but it works !

To improve that the solution would be to add en option in the component configuration to let the user choose the filename of the partial they want to use (instead of default.htm) but, by reading the author reply, it seems it's not possible actually with october cms, so I think the issue can be closed.

**Comment by gwugodevco** [comment]
use: 

> {% component 'forms::form1' %}

create the file under your theme: your-theme/partials/forms/form1.htm

**Comment by Alex360hd** [comment]
Wow, I will test that and if it works, you are a genius !

**Comment by skydiver** [comment]
This works for me.

I don't think the plugin needs any modifications because the solution it's at page level.

**Comment by Alex360hd** [comment]
I confirm, it's managed by october core, so it's not an issue related to this module. Could be closed.

**Comment by rangrage** [comment]
@gwugodevco @Alex360hd can you kindly explain how to implement this please? 

I have created a file in my theme partials/forms/form1.htm, then I created a CMS page with the genericForm component. 

I've aliased the component with 'form1' and on the page I call the component as suggested: 

> {% component 'forms::form1' %} 

But this does not render the form on the page, I've tried aliasing the component as forms::form1 but this give a validation error. 

Can you please let me know what I am missing? 

Thanks.

**Comment by rangrage** [comment]
@skydiver can you have a look at my comment above and let me know how to do this please?

Thanks for your assistance.
